/* UI strings in English and Nepali. Mirrors mobile/strings.js so both clients
   speak the same language in the same words. Disease CONTENT (symptoms, cause,
   treatment...) does not live here - that comes from the API's *_np fields and
   is selected in normalize.js. */

export const LANGS = [
  { id: "en", label: "EN", full: "English" },
  { id: "np", label: "ने", full: "नेपाली" },
];

const en = {
  // nav + chrome
  brand: "CropSense",
  skipToContent: "Skip to content",
  menu: "Menu",
  navHome: "Home",
  navDiagnose: "Diagnose",
  navLibrary: "Disease library",
  navHistory: "History",
  navAbout: "About",
  footerAbout: "About & disclaimer",
  switchToNepali: "नेपालीमा हेर्नुहोस्",
  switchToEnglish: "View in English",

  // home
  homeTitle: "Detect crop diseases early and protect your harvest",
  homeLead: "Photograph an affected leaf to identify the disease and get treatment advice in English or Nepali.",
  checkALeaf: "Check a leaf",
  browseLibrary: "Browse disease library",
  howItWorks: "How it works",
  cropsCovered: "Supported crops",
  cropsCoveredNote: "If the photo isn’t a supported leaf, or the result is unclear, CropSense tells you instead of guessing.",
  readMore: "Learn more",
  step1: "Choose your crop",
  step2: "Add a clear leaf photo",
  step3: "See the disease and treatment",

  // accounts (optional — diagnosis never requires one)
  signIn: "Sign in",
  signOut: "Sign out",
  signInTitle: "Sign in",
  createAccount: "Create account",
  createAccountTitle: "Create an account",
  username: "Username",
  email: "Email",
  password: "Password",
  signingIn: "Signing in…",
  creatingAccount: "Creating account…",
  accountCreated: "Account created. Please sign in.",
  noAccountYet: "Don't have an account?",
  haveAccount: "Already have an account?",
  loginFailed: "Sign in failed. Check your username and password.",
  signupFailed: "Could not create the account.",
  passwordHint: "At least 8 characters.",
  profileTitle: "Your account",
  memberSince: "Member since",
  savedChecks: "Saved leaf checks",
  savedOnServer: "Saved to your account",
  savedOnThisDevice: "Saved on this device only",
  historyServerNote: "Signed in as {user}. These checks are saved to your account and appear on every device.",

  // diagnose
  diagnoseTitle: "Diagnose a leaf",
  diagnoseLead: "Select the crop (or choose “Any crop”), add a clear photo of one affected leaf, then analyze.",
  stepSelectCrop: "1. Select the crop",
  stepAddPhoto: "2. Add a leaf photo",
  cropRequired: "Crop (required)",
  anyCrop: "Any crop — I’m not sure",
  anyCropHint: "The leaf will still be identified across all 10 supported crops. Only the “wrong crop selected” warning is skipped.",
  analyzeLeaf: "Analyze leaf",
  analyzing: "Analyzing leaf…",
  analyzingLive: "Analyzing your leaf photo, please wait.",
  errPickImage: "Please choose an image file.",
  errTooLarge: "That image is larger than 12 MB. Please use a smaller photo.",
  errPickCrop: "Please select a crop first.",
  errNoPhoto: "Please add a leaf photo.",
  errTimeoutTitle: "The analysis timed out",
  errNetworkTitle: "Can’t reach the server",
  errFailedTitle: "Analysis failed",
  errBadImageTitle: "That photo could not be read",
  errBadImageBody: "Please upload a clear JPG, PNG or WEBP photo of a leaf.",

  // image picker
  takePhoto: "Take photo",
  uploadImage: "Upload image",
  developedBy: "Developed by",
  developerName: "Bibek Shah",
  productOfNepal: "Product of Nepal",
  productOfNepalSub: "Built in Nepal, for Nepali farmers",
  nepalFlagAlt: "Flag of Nepal",
  footerTagline: "CropSense provides general crop-care guidance and is not a substitute for professional agricultural advice.",
  photoTips: "For the clearest result",
  tip1: "Use one visible leaf",
  tip2: "Keep the affected area in focus",
  tip3: "Use even, natural lighting",
  tip4: "Avoid overlapping leaves",
  tip5: "Avoid distant or blurry photos",
  selectedPhoto: "Selected leaf photo",
  replacePhoto: "Replace",
  removePhoto: "Remove",
  scanning: "Scanning the leaf…",

  // result
  possibleMatch: "Possible match",
  confidence: "Confidence",
  statusHigh: "High confidence",
  statusModerate: "Moderate confidence",
  statusUncertain: "Uncertain result",
  uncertainTitle: "This result is uncertain.",
  uncertainBody: "Try uploading another clear, well-lit photo of a single affected leaf. For anything important, confirm with a local agricultural expert before treating the crop.",
  notConfident: "The model is not confident about this image.",
  visualExplanation: "Visual explanation",
  yourPhoto: "Your photo",
  modelAttention: "Model attention",
  yourPhotoAlt: "The leaf photo you submitted",
  heatmapAlt: "Heatmap showing the regions that most influenced the model",
  gradcamNote: "Highlighted areas show which parts of the image influenced the model most. This visual explanation does not confirm the diagnosis.",
  guidance: "Crop-care guidance",
  refNote: "The guidance below is general reference for this possible match — not a confirmed diagnosis.",
  description: "Description",
  healthy: "Healthy",
  secSymptoms: "Symptoms",
  secCause: "Cause",
  secTreatment: "General management",
  secPrevention: "Prevention",
  otherPossibilities: "Other possibilities",
  helpful: "Was this result helpful?",
  feedbackSaved: "Thanks — your feedback was saved on this device.",
  checkAnother: "Check another leaf",
  noResult: "No result to show",
  noResultBody: "Start a diagnosis to see the possible disease match and guidance here.",

  // treatment card
  recommendedTreatment: "Recommended treatment",
  activeIngredient: "active ingredient",
  dose: "Dose",
  formulation: "Formulation",
  waitBeforeHarvest: "Wait before harvest",
  repeat: "Repeat",
  safety: "Safety",
  culturalControl: "Cultural control",
  bandIa: "Highly hazardous",
  bandIaNote: "Full protective clothing. Never spray in wind.",
  bandIi: "Moderately hazardous",
  bandIiNote: "Gloves, mask and long sleeves required.",
  bandIii: "Slightly hazardous",
  bandIiiNote: "Gloves and a mask are still recommended.",
  bandU: "Unlikely to be hazardous",
  bandUNote: "Low risk, but still wash hands after use.",
  days: "days",
  treatLead: "Try the non-chemical step first — it costs nothing and leaves no residue. Take this page to your agrovet and ask for the active ingredient named below, not a brand.",
  repeatEvery: (n) => `every ${n} days if symptoms continue`,
  seeLabel: "see label",
  buyingIt: "Buying it at the agrovet",
  buyingItBody: (active, form) =>
    `Ask for the active ingredient by name: ${active}. Brands and packaging differ, so check the pack itself lists that name and the code ${form}, and that its hazard triangle matches the colour above.`,
  buyingItNoCode: (active) =>
    `Ask for the active ingredient by name: ${active}. Brands and packaging differ, so check the pack itself lists that exact name.`,
  formShapePowder: "Sold as a powder in a sealed sachet or packet.",
  formShapeLiquid: "Sold as a liquid in a bottle - measure with a cap or syringe.",
  formShapeGranule: "Sold as granules in a bag - spread dry, do not mix with water.",
  kindCultural: "Cultural practice",
  kindFungicide: "Fungicide",
  kindBiological: "Biological",
  kindDisinfectant: "Disinfectant",
  kindInsecticide: "Insecticide",
  kindBiopesticide: "Biopesticide",
  kindFungicideBactericide: "Fungicide / bactericide",
  kindBactericide: "Bactericide",
  kindAcaricide: "Acaricide (mite killer)",
  formWP: "Wettable powder — mix with water",
  formSP: "Soluble powder — dissolves in water",
  formSC: "Suspension concentrate — shake before measuring",
  formEC: "Emulsifiable concentrate — oily liquid, measure carefully",
  formSL: "Soluble liquid — dissolves in water",
  formG: "Granule — apply to the soil, do not dilute",
  formOL: "Oil formulation — spray in the evening",

  // history
  historyTitle: "Prediction history",
  historyLead: "Your recent checks are saved on this device.",
  historyEmpty: "No checks yet.",
  countShown: (n, total) => `${n} of ${total} shown`,
  search: "Search",
  searchPlaceholder: "Search disease or crop",
  filterByCrop: "Filter by crop",
  filterByStatus: "Filter by status",
  allCrops: "All crops",
  allStatuses: "All statuses",
  sortOrder: "Sort order",
  newestFirst: "Newest first",
  oldestFirst: "Oldest first",
  details: "Details",
  deleteAll: "Delete all",
  deleteAllConfirm: (n) => `Delete all ${n} saved checks? This cannot be undone.`,
  deleteAllYes: "Yes, delete all",
  cancel: "Cancel",
  deleteOne: "Delete",
  deleteOneLabel: (disease) => `Delete the saved check for ${disease}`,
  historyCleared: "All saved checks were deleted.",

  // library
  libraryTitle: "Disease library",
  searchDiseases: "Search diseases",
  searchDiseasePlaceholder: "Search by disease or symptom",
  viewDetails: "View details →",
  backToLibrary: "← Back to library",
  backToLibraryBtn: "Back to library",
  entryNotFound: "Entry not found",
  entryNotFoundBody: "That disease entry does not exist.",
  backToHistory: "Back to history",
  backToHistoryLink: "← Back to history",
  checkNotFound: "Check not found",
  checkNotFoundBody: "This saved check is no longer available on this device.",
  navPrimary: "Primary",
  navFooter: "Footer",
  feedbackRegion: "Feedback",

  // about + misc
  aboutTitle: "About & disclaimer",
  aboutLead: "What this tool does, and how to use its results responsibly.",
  whatItDoes: "What it does",
  aboutWhatBody: "CropSense looks at a photo of a single crop leaf and suggests a possible disease match. It reports how confident it is, highlights the parts of the image that influenced that answer, and gives general symptoms, likely cause, management and prevention notes in English and Nepali.",
  aboutHow: "How it works",
  aboutHowStep1: "You choose the crop and add a clear photo of one affected leaf.",
  aboutHowStep2: "The app first checks the photo actually looks like a leaf, and crops in on it so a cluttered field background does not confuse the model.",
  aboutHowStep3: "An EfficientNetB2 neural network, trained on tens of thousands of labelled leaf images, scores the photo against every condition it knows.",
  aboutHowStep4: "If the result is doubtful the app says so instead of guessing, and shows the runner-up possibilities.",
  aboutHowStep5: "You get the guidance, a heat map of what the model looked at, and treatment options - non-chemical first.",
  aboutCoverage: "What it covers",
  aboutCoverageBody: "51 diseases and healthy states across these 10 crops:",
  aboutCoverageNote: "Anything outside this list - a crop it was never trained on, or a photo that is not a leaf - should be reported as unsupported rather than guessed at.",
  aboutConfidence: "Reading the confidence",
  aboutConfHigh: "High - 80% or more. The model matched this strongly, but still confirm anything costly.",
  aboutConfModerate: "Moderate - 60% to 80%. Worth acting on cautiously; a second photo helps.",
  aboutConfUncertain: "Uncertain - below 60%, or the app flagged a problem such as a blurry photo or the wrong crop. Treat it as a hint only.",
  aboutUnsure: "When it says it is not sure",
  aboutUnsureBody: "A tool that always answers is not honest. This one declines in three situations: the photo does not look like a leaf, the leaf belongs to a crop it was never trained on, or the prediction is too close to call. Getting a clear refusal is more useful than a confident wrong answer that sends you to buy the wrong chemical.",
  aboutPrivacy: "Your photos and data",
  aboutPrivacyBody: "Photos are analysed and discarded - nothing is stored on the server. Your check history is saved only in this browser on this device, so it needs no account and never leaves your phone or computer. Clearing your browser data clears the history.",
  aboutLimitationsBody: "Most training images were taken in controlled conditions. Real field photos vary in light, background and disease stage, so accuracy outdoors is lower than in testing. The model names one disease per leaf, so it cannot describe two diseases at once, nutrient problems that mimic disease, or how severe an infection is. The heat map shows where the model looked - it does not prove the answer is right.",
  aboutDisclaimerBody: "This tool gives general guidance only and is not a substitute for professional agricultural advice. Treatment information, including doses and pre-harvest intervals, has not been reviewed by a licensed agronomist. Always read the product label and confirm any important decision with your agrovet or local agriculture office before spraying.",
  aboutProject: "About the project",
  aboutProjectBody: "CropSense was built as a Final Year Project to explore whether a phone photo can give smallholder farmers a useful first opinion on crop disease, in their own language, without needing an account or a constant internet connection.",
  limitations: "Limitations",
  disclaimer: "Disclaimer",
  notFound: "Page not found",
  notFoundBody: "The page you were looking for doesn't exist or has moved.",
  backHome: "Back to home",
  loading: "Loading",
  somethingWrong: "Something went wrong",
  retry: "Try again",
};

const np = {
  brand: "CropSense",
  skipToContent: "मुख्य सामग्रीमा जानुहोस्",
  menu: "मेनु",
  navHome: "गृहपृष्ठ",
  navDiagnose: "रोग पहिचान",
  navLibrary: "रोग सूची",
  navHistory: "इतिहास",
  navAbout: "बारेमा",
  footerAbout: "बारेमा र अस्वीकरण",
  switchToNepali: "नेपालीमा हेर्नुहोस्",
  switchToEnglish: "View in English",

  homeTitle: "बालीका रोग समयमै पहिचान गर्नुहोस्, उब्जनी जोगाउनुहोस्",
  homeLead: "रोग लागेको पातको तस्बिर लिनुहोस् र रोगको पहिचानसँगै उपचारको सल्लाह नेपाली वा अंग्रेजीमा पाउनुहोस्।",
  checkALeaf: "पात जाँच्नुहोस्",
  browseLibrary: "रोग सूची हेर्नुहोस्",
  howItWorks: "यसले कसरी काम गर्छ",
  cropsCovered: "समर्थित बाली",
  cropsCoveredNote: "तस्बिर समर्थित पातको नभए वा नतिजा स्पष्ट नभए CropSense ले अनुमान नलगाई त्यही बताउँछ।",
  readMore: "थप जानकारी",
  step1: "बाली छान्नुहोस्",
  step2: "पातको स्पष्ट तस्बिर थप्नुहोस्",
  step3: "रोग र उपचार हेर्नुहोस्",

  // accounts
  signIn: "साइन इन",
  signOut: "साइन आउट",
  signInTitle: "साइन इन गर्नुहोस्",
  createAccount: "खाता खोल्नुहोस्",
  createAccountTitle: "नयाँ खाता खोल्नुहोस्",
  username: "प्रयोगकर्ता नाम",
  email: "इमेल",
  password: "पासवर्ड",
  signingIn: "साइन इन गर्दै…",
  creatingAccount: "खाता खोल्दै…",
  accountCreated: "खाता खोलियो। अब साइन इन गर्नुहोस्।",
  noAccountYet: "खाता छैन?",
  haveAccount: "पहिल्यै खाता छ?",
  loginFailed: "साइन इन भएन। प्रयोगकर्ता नाम र पासवर्ड जाँच्नुहोस्।",
  signupFailed: "खाता खोल्न सकिएन।",
  passwordHint: "कम्तीमा ८ अक्षर।",
  profileTitle: "तपाईंको खाता",
  memberSince: "सदस्य भएको मिति",
  savedChecks: "सुरक्षित जाँचहरू",
  savedOnServer: "तपाईंको खातामा सुरक्षित",
  savedOnThisDevice: "यही यन्त्रमा मात्र सुरक्षित",
  historyServerNote: "{user} को रूपमा साइन इन। यी जाँचहरू तपाईंको खातामा सुरक्षित छन् र हरेक यन्त्रबाट देखिन्छन्।",

  diagnoseTitle: "पातको रोग पहिचान",
  diagnoseLead: "बाली छान्नुहोस् (वा “जुनसुकै बाली” रोज्नुहोस्), रोग लागेको एउटै पातको स्पष्ट तस्बिर थप्नुहोस् र विश्लेषण गर्नुहोस्।",
  stepSelectCrop: "१. बाली छान्नुहोस्",
  stepAddPhoto: "२. पातको तस्बिर थप्नुहोस्",
  cropRequired: "बाली (अनिवार्य)",
  anyCrop: "जुनसुकै बाली — मलाई थाहा छैन",
  anyCropHint: "पात अझै पनि सबै १० वटा बालीमध्येबाट पहिचान गरिनेछ। केवल “गलत बाली छानियो” भन्ने चेतावनी मात्र देखिँदैन।",
  analyzeLeaf: "पात विश्लेषण गर्नुहोस्",
  analyzing: "विश्लेषण गर्दै…",
  analyzingLive: "तपाईंको पातको तस्बिर विश्लेषण गर्दै छ, कृपया पर्खनुहोस्।",
  errPickImage: "कृपया तस्बिर फाइल छान्नुहोस्।",
  errTooLarge: "यो तस्बिर १२ एम.बी. भन्दा ठूलो छ। कृपया सानो तस्बिर प्रयोग गर्नुहोस्।",
  errPickCrop: "कृपया पहिले बाली छान्नुहोस्।",
  errNoPhoto: "कृपया पातको तस्बिर थप्नुहोस्।",
  errTimeoutTitle: "विश्लेषण गर्न धेरै समय लाग्यो",
  errNetworkTitle: "सर्भरसँग सम्पर्क हुन सकेन",
  errFailedTitle: "विश्लेषण असफल भयो",
  errBadImageTitle: "यो तस्बिर पढ्न सकिएन",
  errBadImageBody: "कृपया पातको स्पष्ट JPG, PNG वा WEBP तस्बिर अपलोड गर्नुहोस्।",

  takePhoto: "तस्बिर खिच्नुहोस्",
  uploadImage: "तस्बिर अपलोड गर्नुहोस्",
  developedBy: "विकासकर्ता",
  developerName: "बिबेक शाह",
  productOfNepal: "नेपालमा निर्मित",
  productOfNepalSub: "नेपाली किसानका लागि, नेपालमै बनाइएको",
  nepalFlagAlt: "नेपालको झन्डा",
  footerTagline: "क्रपसेन्सले बाली हेरचाहसम्बन्धी सामान्य सल्लाह मात्र दिन्छ। यो कृषि विज्ञको व्यावसायिक सल्लाहको विकल्प होइन।",
  photoTips: "राम्रो नतिजाका लागि",
  tip1: "एउटै पात स्पष्ट देखिने गरी खिच्नुहोस्",
  tip2: "रोग लागेको भाग फोकसमा राख्नुहोस्",
  tip3: "समान र प्राकृतिक उज्यालोमा खिच्नुहोस्",
  tip4: "पातहरू एकआपसमा नछोपिने गर्नुहोस्",
  tip5: "टाढाबाट वा धमिलो तस्बिर नखिच्नुहोस्",
  selectedPhoto: "छानिएको पातको तस्बिर",
  replacePhoto: "बदल्नुहोस्",
  removePhoto: "हटाउनुहोस्",
  scanning: "पात स्क्यान गर्दै…",

  possibleMatch: "सम्भावित रोग",
  confidence: "विश्वसनीयता",
  statusHigh: "उच्च विश्वसनीयता",
  statusModerate: "मध्यम विश्वसनीयता",
  statusUncertain: "अनिश्चित नतिजा",
  uncertainTitle: "यो नतिजा अनिश्चित छ।",
  uncertainBody: "रोग लागेको एउटै पातको स्पष्ट र राम्रो उज्यालोमा खिचेको अर्को तस्बिर पठाएर हेर्नुहोस्। महत्त्वपूर्ण निर्णय गर्नु अघि स्थानीय कृषि विज्ञसँग पक्का गर्नुहोस्।",
  notConfident: "यो तस्बिरबारे मोडेल विश्वस्त छैन।",
  visualExplanation: "दृश्य व्याख्या",
  yourPhoto: "तपाईंको तस्बिर",
  modelAttention: "मोडेलले हेरेको भाग",
  yourPhotoAlt: "तपाईंले पठाउनुभएको पातको तस्बिर",
  heatmapAlt: "मोडेललाई सबैभन्दा बढी प्रभाव पारेका भागहरू देखाउने रङ्गीन नक्सा",
  gradcamNote: "रङ्गिएका भागहरूले तस्बिरका कुन भागले मोडेललाई सबैभन्दा बढी प्रभाव पारे भन्ने देखाउँछ। यो दृश्य व्याख्याले रोगको पुष्टि गर्दैन।",
  guidance: "बाली हेरचाह सल्लाह",
  refNote: "तल दिइएको सल्लाह यो सम्भावित रोगका लागि सामान्य जानकारी मात्र हो — यो पुष्टि भएको निदान होइन।",
  description: "विवरण",
  healthy: "स्वस्थ",
  secSymptoms: "लक्षण",
  secCause: "कारण",
  secTreatment: "सामान्य व्यवस्थापन",
  secPrevention: "रोकथाम",
  otherPossibilities: "अन्य सम्भावनाहरू",
  helpful: "यो नतिजा उपयोगी थियो?",
  feedbackSaved: "धन्यवाद — तपाईंको प्रतिक्रिया यही यन्त्रमा सुरक्षित गरियो।",
  checkAnother: "अर्को पात जाँच्नुहोस्",
  noResult: "देखाउन कुनै नतिजा छैन",
  noResultBody: "सम्भावित रोग र सल्लाह यहाँ हेर्न पहिले पातको जाँच सुरु गर्नुहोस्।",

  recommendedTreatment: "सिफारिस गरिएको उपचार",
  activeIngredient: "सक्रिय तत्व",
  dose: "मात्रा",
  formulation: "औषधिको प्रकार",
  waitBeforeHarvest: "टिप्नु अघि पर्खने",
  repeat: "दोहोर्‍याउने अन्तराल",
  safety: "सुरक्षा",
  culturalControl: "खेती प्रविधिबाट नियन्त्रण",
  bandIa: "अत्यन्त खतरनाक",
  bandIaNote: "पूरा सुरक्षा पोशाक लगाउनुहोस्। हावा चलेको बेला कहिल्यै नछर्नुहोस्।",
  bandIi: "मध्यम खतरनाक",
  bandIiNote: "पन्जा, मास्क र लामो बाहुला अनिवार्य छ।",
  bandIii: "अलिकति खतरनाक",
  bandIiiNote: "पन्जा र मास्क लगाउन सिफारिस गरिन्छ।",
  bandU: "कम जोखिमयुक्त",
  bandUNote: "जोखिम कम छ, तर प्रयोगपछि हात धुनुहोस्।",
  days: "दिन",
  treatLead: "पहिले रसायन नचाहिने उपाय अपनाउनुहोस् — यसमा खर्च लाग्दैन र कुनै अवशेष रहँदैन। यो पृष्ठ आफ्नो कृषि पसलमा लैजानुहोस् र तल लेखिएको सक्रिय तत्व मागुनहोस्, ब्रान्डको नाम होइन।",
  repeatEvery: (n) => `लक्षण जारी रहे हरेक ${n} दिनमा दोहोर्\u200dयाउनुहोस्`,
  seeLabel: "लेबल हेर्नुहोस्",
  buyingIt: "कृषि पसलमा किन्दा",
  buyingItBody: (active, form) =>
    `सक्रिय तत्वको नाम लिएर माग्नुहोस्: ${active}। ब्रान्ड र प्याकेजिङ फरक हुन्छ, त्यसैले प्याकेटमै त्यही नाम र ${form} कोड लेखिएको छ कि छैन जाँच्नुहोस्, र त्यसको खतराको त्रिकोण माथि देखाइएको रङसँग मिल्नुपर्छ।`,
  buyingItNoCode: (active) =>
    `सक्रिय तत्वको नाम लिएर माग्नुहोस्: ${active}। ब्रान्ड र प्याकेजिङ फरक हुन्छ, त्यसैले प्याकेटमै ठ्याक्कै त्यही नाम लेखिएको छ कि छैन जाँच्नुहोस्।`,
  formShapePowder: "बन्द प्याकेट वा पोकोमा धुलोको रूपमा पाइन्छ।",
  formShapeLiquid: "बोतलमा झोलको रूपमा पाइन्छ — बिर्को वा सिरिन्जले नाप्नुहोस्।",
  formShapeGranule: "झोलामा दानाको रूपमा पाइन्छ — सुक्खै छर्नुहोस्, पानीमा नमिसाउनुहोस्।",
  kindCultural: "खेती प्रविधि",
  kindFungicide: "ढुसीनाशक",
  kindBiological: "जैविक",
  kindDisinfectant: "कीटाणुनाशक",
  kindInsecticide: "कीटनाशक",
  kindBiopesticide: "जैविक विषादी",
  kindFungicideBactericide: "ढुसीनाशक / ब्याक्टेरियानाशक",
  kindBactericide: "ब्याक्टेरियानाशक",
  kindAcaricide: "माइटनाशक",
  formWP: "पानीमा घोल्ने धुलो (WP) — पानीमा मिसाउनुहोस्",
  formSP: "घुलनशील धुलो (SP) — पानीमा घुल्छ",
  formSC: "सस्पेन्सन कन्सन्ट्रेट (SC) — नाप्नु अघि हल्लाउनुहोस्",
  formEC: "इमल्सिफाएबल कन्सन्ट्रेट (EC) — तेलिलो झोल, ध्यानपूर्वक नाप्नुहोस्",
  formSL: "घुलनशील झोल (SL) — पानीमा घुल्छ",
  formG: "दाना (G) — माटोमा हाल्नुहोस्, पानीमा नमिसाउनुहोस्",
  formOL: "तेल आधारित (OL) — साँझमा छर्नुहोस्",

  historyTitle: "जाँचको इतिहास",
  historyLead: "तपाईंले हालै गर्नुभएका जाँचहरू यही यन्त्रमा सुरक्षित छन्।",
  historyEmpty: "अहिलेसम्म कुनै जाँच गरिएको छैन।",
  countShown: (n, total) => `${total} मध्ये ${n} देखाइएको`,
  search: "खोज्नुहोस्",
  searchPlaceholder: "रोग वा बालीको नामले खोज्नुहोस्",
  filterByCrop: "बाली अनुसार छान्नुहोस्",
  filterByStatus: "स्थिति अनुसार छान्नुहोस्",
  allCrops: "सबै बाली",
  allStatuses: "सबै स्थिति",
  sortOrder: "क्रम मिलाउनुहोस्",
  newestFirst: "नयाँ पहिले",
  oldestFirst: "पुरानो पहिले",
  details: "विवरण",
  deleteAll: "सबै मेटाउनुहोस्",
  deleteAllConfirm: (n) => `सुरक्षित गरिएका सबै ${n} वटा जाँच मेटाउने? यो फिर्ता ल्याउन सकिँदैन।`,
  deleteAllYes: "हो, सबै मेटाउनुहोस्",
  cancel: "रद्द गर्नुहोस्",
  deleteOne: "मेटाउनुहोस्",
  deleteOneLabel: (disease) => `${disease} को सुरक्षित जाँच मेटाउनुहोस्`,
  historyCleared: "सुरक्षित गरिएका सबै जाँच मेटाइयो।",

  libraryTitle: "रोग सूची",
  searchDiseases: "रोग खोज्नुहोस्",
  searchDiseasePlaceholder: "रोग वा लक्षणले खोज्नुहोस्",
  viewDetails: "विवरण हेर्नुहोस् →",
  backToLibrary: "← रोग सूचीमा फर्कनुहोस्",
  backToLibraryBtn: "रोग सूचीमा फर्कनुहोस्",
  entryNotFound: "विवरण भेटिएन",
  entryNotFoundBody: "त्यो रोगको विवरण उपलब्ध छैन।",
  backToHistory: "इतिहासमा फर्कनुहोस्",
  backToHistoryLink: "← इतिहासमा फर्कनुहोस्",
  checkNotFound: "जाँच भेटिएन",
  checkNotFoundBody: "यो सुरक्षित गरिएको जाँच अब यस यन्त्रमा उपलब्ध छैन।",
  navPrimary: "मुख्य",
  navFooter: "फुटर",
  feedbackRegion: "प्रतिक्रिया",

  aboutTitle: "बारेमा र अस्वीकरण",
  aboutLead: "यो उपकरणले के गर्छ र यसको नतिजा कसरी जिम्मेवारीपूर्वक प्रयोग गर्ने।",
  whatItDoes: "यसले के गर्छ",
  aboutWhatBody: "क्रपसेन्सले बालीको एउटै पातको तस्बिर हेरेर सम्भावित रोग सुझाउँछ। यसले आफ्नो विश्वसनीयता कति छ भन्ने देखाउँछ, तस्बिरको कुन भागले नतिजा निर्धारण गर्‍यो भनी उजागर गर्छ, र लक्षण, सम्भावित कारण, व्यवस्थापन तथा रोकथामसम्बन्धी सामान्य जानकारी अंग्रेजी र नेपाली दुवैमा दिन्छ।",
  aboutHow: "यसले कसरी काम गर्छ",
  aboutHowStep1: "तपाईं बाली छान्नुहुन्छ र रोग लागेको एउटै पातको स्पष्ट तस्बिर थप्नुहुन्छ।",
  aboutHowStep2: "एपले पहिले तस्बिर साँच्चै पातकै हो कि होइन जाँच्छ, र खेतको भीडभाड पृष्ठभूमिले अल्मल्याउन नपाओस् भनी पातमै केन्द्रित गर्छ।",
  aboutHowStep3: "हजारौं लेबल गरिएका पातका तस्बिरमा तालिम पाएको EfficientNetB2 न्युरल नेटवर्कले तस्बिरलाई आफूले चिनेका सबै अवस्थासँग तुलना गर्छ।",
  aboutHowStep4: "नतिजा शंकास्पद भएमा एपले अनुमान नलगाई त्यही कुरा बताउँछ, र अन्य सम्भावनाहरू पनि देखाउँछ।",
  aboutHowStep5: "तपाईंले सल्लाह, मोडेलले हेरेको भाग देखाउने रङ्गीन नक्सा र उपचारका विकल्प पाउनुहुन्छ — पहिले रसायन नचाहिने उपाय।",
  aboutCoverage: "यसले के-के समेट्छ",
  aboutCoverageBody: "यी १० बालीका ५१ रोग तथा स्वस्थ अवस्थाहरू:",
  aboutCoverageNote: "यो सूची बाहिरको कुनै कुरा — तालिम नपाएको बाली वा पात नभएको तस्बिर — अनुमान नगरी \u201cसमर्थित छैन\u201d भनी जनाइनुपर्छ।",
  aboutConfidence: "विश्वसनीयता कसरी बुझ्ने",
  aboutConfHigh: "उच्च — ८०% वा बढी। मोडेल बलियो रूपमा मिल्यो, तर खर्चिलो निर्णय गर्नु अघि पक्का गर्नुहोस्।",
  aboutConfModerate: "मध्यम — ६०% देखि ८०%। सावधानीपूर्वक काम गर्न सकिन्छ; अर्को तस्बिरले मद्दत गर्छ।",
  aboutConfUncertain: "अनिश्चित — ६०% भन्दा कम, वा धमिलो तस्बिर तथा गलत बालीजस्ता समस्या देखिएमा। यसलाई संकेत मात्र मान्नुहोस्।",
  aboutUnsure: "जब यसले \u201cपक्का छैन\u201d भन्छ",
  aboutUnsureBody: "सधैं जवाफ दिने उपकरण इमानदार हुँदैन। यसले तीन अवस्थामा जवाफ दिन अस्वीकार गर्छ: तस्बिर पातजस्तो देखिँदैन, पात तालिम नपाएको बालीको हो, वा नतिजा छुट्याउनै गाह्रो छ। गलत औषधि किन्न पठाउने आत्मविश्वासी गलत जवाफभन्दा स्पष्ट अस्वीकार बढी उपयोगी हुन्छ।",
  aboutPrivacy: "तपाईंका तस्बिर र तथ्याङ्क",
  aboutPrivacyBody: "तस्बिर विश्लेषण गरेर हटाइन्छ — सर्भरमा केही पनि सुरक्षित गरिँदैन। तपाईंको जाँचको इतिहास यही यन्त्रको ब्राउजरमा मात्र सुरक्षित हुन्छ, त्यसैले खाता चाहिँदैन र यो तपाईंको फोन वा कम्प्युटरबाट कतै जाँदैन। ब्राउजरको डाटा मेटाएमा इतिहास पनि मेटिन्छ।",
  aboutLimitationsBody: "अधिकांश तालिम तस्बिरहरू नियन्त्रित अवस्थामा खिचिएका थिए। वास्तविक खेतका तस्बिरमा उज्यालो, पृष्ठभूमि र रोगको अवस्था फरक हुन्छ, त्यसैले बाहिरको शुद्धता परीक्षणभन्दा कम हुन्छ। मोडेलले एउटा पातमा एउटै रोग तोक्छ, त्यसैले एकैपटक दुई रोग, रोगजस्तै देखिने पोषणको समस्या, वा संक्रमण कति गम्भीर छ भन्ने कुरा यसले बताउन सक्दैन। रङ्गीन नक्साले मोडेलले कहाँ हेर्‍यो भन्ने देखाउँछ — जवाफ सही हो भनी प्रमाणित गर्दैन।",
  aboutDisclaimerBody: "यो उपकरणले सामान्य जानकारी मात्र दिन्छ र यो कृषि विज्ञको व्यावसायिक सल्लाहको विकल्प होइन। मात्रा र बाली टिप्नु अघिको प्रतीक्षा अवधिसहितका उपचार जानकारी इजाजतप्राप्त कृषि विज्ञद्वारा समीक्षा गरिएको छैन। सधैं औषधिको लेबल पढ्नुहोस् र छर्नु अघि महत्त्वपूर्ण निर्णय आफ्नो कृषि पसल वा स्थानीय कृषि कार्यालयसँग पक्का गर्नुहोस्।",
  aboutProject: "परियोजनाको बारेमा",
  aboutProjectBody: "क्रपसेन्स स्नातक तहको अन्तिम वर्षको परियोजनाका रूपमा बनाइएको हो। यसको उद्देश्य हो — फोनबाट खिचेको एउटा तस्बिरले साना किसानलाई आफ्नै भाषामा, खाता वा निरन्तर इन्टरनेट नचाहिने गरी, बालीको रोगबारे उपयोगी प्रारम्भिक राय दिन सक्छ कि सक्दैन भनी हेर्नु।",
  limitations: "सीमाहरू",
  disclaimer: "अस्वीकरण",
  notFound: "पृष्ठ भेटिएन",
  notFoundBody: "तपाईंले खोज्नुभएको पृष्ठ अवस्थित छैन वा सारिएको छ।",
  backHome: "गृहपृष्ठमा फर्कनुहोस्",
  loading: "लोड हुँदै",
  somethingWrong: "केही गडबड भयो",
  retry: "फेरि प्रयास गर्नुहोस्",
};

export const STRINGS = { en, np };
